# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-19 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180517_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='want_to_say',
            field=models.CharField(blank=True, max_length=200, verbose_name='想说的话'),
        ),
    ]
