# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-20 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_want_to_say'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='是否轮播'),
        ),
    ]
