# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-21 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_is_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='管理权限'),
        ),
    ]
